### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by mil-lesya** [pocketfi/pocketfi#101]
This feature is intended for analytics personal expense and income.

- [ ] Expense / income / saving by time
- [ ] Expense by category
- [ ] Expence by place
- [ ] Income by place
- [ ] Exceeding the limits
- [ ] Income distribution diagram by type of expense
- [ ] Money transfer tree
