### ISSUE TITLE
Bank statement support

### ISSUE THREAD

**Issue by ivanjermakov** [pocketfi/pocketfi#95]
This feature will enable uploading credit card bank statements to automate transaction creation.

Investigate:
- [ ] Bank statement types (on-demand, month report etc.)
- [ ] Bank statement file types (`pdf`, `xls`, `csv`, `html` etc.)
- [ ] Parsing libraries

Workflow:
- [ ] Search for the bank by name/country/bic
- [ ] Determine wether bank is supported and what statement types/formats
- [ ] Display guide for getting statement from bank
- [ ] Upload statement
- [ ] Parse statement
- [ ] Show list of parsed transactions
     * [ ] Allow transaction edit
     * [ ] Bulk category edit with "remember" option
- [ ] Confirm merging parsed transactions into the account

Other tickets:
- [x] Backend architecture #96

Document settings (* - required):
- *Issuer (bank)
- *File format
- *File format details (if `csv`)
- *Date format
- *Encoding
- Report type
- Document version format

**Comment by ivanjermakov** [comment]
We need an API to lookup banks.
I found this API: https://bankcodesapi.com/users/api-swift-code/
They provide a free country/bank name API for verified users, currently waiting for the verification.

**Comment by ivanjermakov** [comment]
We should parse the banks from some other service since we just need a list of bank names by country.
A great solution will be to create an automated web-scraper so we can update our bank list.
